### PR TITLE
Add JPype support

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**
This PR adds JPype support, which allows it to be used with regular Python. It is approximately 3 times slower than the GraalVM version, which is 10 time slower than Java.

### CODE REVIEW

**Comment by Thrameos** [comment]
Any issues in JPype that I need to address?   Rough spots, unexpected behaviors, needed improvements?

**Comment by Christopher-Chianelli** [comment]
@Thrameos Thanks for your work on maintaining JPype! Some issues I encountered:

- Ambiguous overloads when there both a varargs and a specific # of args:
If I remove the brackets around the joiners from one of the constraints like so:
```
    return constraintFactory \
            .fromUniquePair(LessonClass,
            # ... in the same timeslot ...
                Joiners.equal(lambda lesson: lesson.timeslot),
            # ... in the same room ...
                Joiners.equal(lambda lesson: lesson.room)) \
            .penalize("Room conflict", HardSoftScore.ONE_HARD)
```
I get the following
```
TypeError: Ambiguous overloads found for org.optaplanner.core.impl.score.stream.InnerConstraintFactory.fromUniquePair(java.lang.Class,org.optaplanner.core.impl.score.stream.bi.SingleBiJoiner,org.optaplanner.core.impl.score.stream.bi.SingleBiJoiner) between:
	public default org.optaplanner.core.api.score.stream.bi.BiConstraintStream org.optaplanner.core.api.score.stream.ConstraintFactory.fromUniquePair(java.lang.Class,org.optaplanner.core.api.score.stream.bi.BiJoiner,org.optaplanner.core.api.score.stream.bi.BiJoiner)
	public default org.optaplanner.core.api.score.stream.bi.BiConstraintStream org.optaplanner.core.api.score.stream.ConstraintFactory.fromUniquePair(java.lang.Class,org.optaplanner.core.api.score.stream.bi.BiJoiner[])
```
I work around this by putting square brackets around the Joiners, which remove the ambiguity (but is more painful to write). 
This is caused by the following interface: https://github.com/kiegroup/optaplanner/blob/28762e3b9c8ffc6c5637b222bfe9d4674c69db37/optaplanner-core/src/main/java/org/optaplanner/core/api/score/stream/ConstraintFactory.java#L139-L185 ; the reason for the overloads with specific # of arguments is: "This method causes <i>Unchecked generics array creation for varargs parameter</i> warnings, but we can't fix it with a {@link SafeVarargs} annotation because it's an interface method. Therefore, there are overloaded methods with up to 4 {@link BiJoiner} parameters." In Java + GraalVM, if there are two methods that can be used, the more specific statically known method is used unless an arg was cast to a less specific type (that is, the three args version would be preferred over the varargs version).

- Would be nice to have an opaque pointer to pass between OptaPlanner and Python. I get around this by using the `id` of the Python object, which is the C pointer to its memory address (Python does `ctypes.cast(objectId, ctypes.py_object).value` to get back its actual value, and passes `id(pythonObject)` to Java). Due to this, I also need to keep a set of references to clones so I do not segfault (as the Python Garbage Collector will collect the clone since it is blissfully unaware that Java still has references to it).

- Overriding `__getattr__` in `@JImplementationFor` can easily cause infinite recursion, since it is called to resolve Java methods. I get around this by passing the Object back to Java in order to call it methods.

- Ability to use Java annotations as decorators and a method to get said Java annotations on a Python Object. OptaPlanner uses annotations to discover what are the planning variables, sources for the planning variables etc. Although I don't expect to be able to pass a Python class/method directly to Java, being able to read Java Annotations without redefining them as decorators would simpify the code. (Currently, I generate the bytecode for the Java wrapper of Python classes, which also has the annotations OptaPlanner needs in order to read the model).

- It is annoying Python lists do not automatically cast to Java Lists. And that if those lists has lists, you also need to map those lists to Java Lists; etc. Same for Python dict to Java Map.

**Comment by Thrameos** [comment]
As for the specific overloads, that is established by Java code in org.jpype.    It is possible to adjust those rules.   If two methods match and neither has the other in the override list then the error is issues.   In order to make the more specific one with two arguments be listed as more specific the code in ``jpype/native/java/org/jpype/manager/MethodResolution.java``.   I have tried to keep the rules matching Java whereever possible.

Though I agree that is appears to be a miss in this case as the following code compiles in Java.
```
public class Foo
{
  static void foo(Object... o)
  {
  }

  static void foo(Object o, Object o2)
  {
  }

  static void bar()
  {
    Object o = null, o2 = null;
    foo(o, o2);
  }
}
```

**Comment by Thrameos** [comment]
As for an opaque pointer, there is a trick using JProxy that allows you to use a generic empty interface like Serializable to hold a Python object in Java and retrieve.  It has the significant downside that if that object is a container which is holding Java objects you will produce an irresolvable reference loop.   Though the same thing will happen with your solution so either way reference loops will be encountered.   Java lacks any hooks to allow a foreign reference counting system to be handled.  I have tried messing with the Java Remote protocols to see if I can get Python and Java to play nice, but thus far have not come up with anything workable.

The JProxy can be combined with a weak-ref to allow for cycle free activity, but you have to hold the Python reference so that it doesn't go away.

For details on how to hold Python objects as opaque objects see the section "Proxying Python objects" in the users guide.

**Comment by Thrameos** [comment]
With regard to ``__getattr__``, yes that is likely a bad method to overload.  Python has differences between ``__getattribute__`` and ``__getattr__`` that I was not well aware of at the time.   It may be possible to improve the pattern in JPype to make it a bit more safe.  If you can construct a small test problem the demonstrates the issue I can see if there is a resolution.

**Comment by Thrameos** [comment]
With regard to annotations, I have access to a lot of those sort of features using reflection, so it is possible that we can recognize something that should operate as annotation and make automatically create a Python decorator.   I suppose it would be best if you gave an example of the preferred syntax that I can work from.   I cant guarantee that I can get it to work, but I certainly can get it to try.

**Comment by Thrameos** [comment]
With regard to Python lists and maps.   Those features are working in the ``epype`` version of ``jpype`` in which Java can call Python code.   You can create a customizer within Java and it will automatically write bytecode using ASM to make a Java version of any Python class.   I customized all the Python containers to map automatically into the corresponding Java container types.   It was an effort I worked on about 6 months back which I am taking a break from because I have not gotten a critical mass of developers to help with.   It was easy to add a foreign call interface from Python to Java and I successful demonstrated it.  However, to be viable I need test cases for every Python call exercised from within Java.    If I can find enough people that are willing to put in the time to develop that test bench it can be releases.   As of now it remains a toy demonstration.   I am pleased with the syntax and as it makes ``python.lang`` a first class type tree in Java and lets you mix and match Python and Java code pretty easily (like calling matplotlib from Java), but it was outside the scope of my job responsibilities so I could not support the time without other developers assistance.

There are some rough edges.   For example currently Python strings are copied to Java strings when passed, but when the wrapper layer is introduced the instead become CPythonString which derives from CharSequence types.  I can still define automatic converters so that Python types convert rather get passed as native Python types but that causes ambiguities thus it does lead to potential code breakage.   So it can't really be released until JPype 2.0.   Same thing happens with int, float, and Number as Python natives map the Number not specific types.   This means code like placing a native Python type in a ``HashMap<String, Integer>`` with ``obj['foo']= 1`` ends up with Number rather than Integer because reflection does not expose the type so all I see is "Object" and the base mapped item will be CPythonInt type.   All of it is entirely doable, just more effort that I can afford right now.
  
My other hesitancy is that just like allowing opaque Python objects into Java (which is doable with the JProxy), this would make it way easier to write reference looped codes.   And I have not found any documentation in Java that would make it possible to resolve this well.   I need much greater levels of support from OpenJDK to make that possible at which point I would likely be recreating Graalvm.

**Comment by Thrameos** [comment]
With regard to speed,  I have cut the overhead by several orders of magnitude already, but my hotspots may not match your usage.  Every time you go over the JNI boundary there is a marshalling cost so cutting trips is important.    If you have a large number of similar items or such passing through adding a cache so that I don't have to go back through JNI to get the same result can speed things up.   

For example, we use caching on the method resolution which is the largest overhead in the system.   Every time a method is called we have to pay the cost of seeing which overload in Java is required and how to convert each of the arguments.  I added a cache so that if the same argument types come through the same resolution method is called (bypassing the overload resolution process.)   This does prevent resolving overloads for things like "list of strings" vs "list of ints" as the type system only sees Python list and not the contents.  And if you do something like alternating between two overloads "foo(String); foo(int); foo(String); foo(int)" it will not get the benefits of the cache which forces the resolution.   I have planned to expose methods more directly so that you can pull out a specific overload and use it repeatedly which bypasses the resolution process entirely, but having found a compelling use case.

Specific paths such as marshalling large numbers of primitives, converting many items on lists for list comprehensions and the overload resolution for tight loops have been dealt with already at user request.   My benchmarking indicates that JPype is the fastest interface of its type with its security ( you can go faster, but you would have to skip safety checks leading to segfaults) in all the places that I checked.   But if you can identify another path which is resulting in a bottle neck, I would be happy to see about optimizing it.    For example sometimes having more arguments pass from Java to Python can save a few round trips through JNI, but unless I see that it is a bottle neck at a specific location I won't cut the trips as the complexity of the interface grows with arguments.

**Comment by Christopher-Chianelli** [comment]
@Thrameos Thanks for your responses. Using the `JProxy(java.io.Serializable)` trick improved performance a bit (~1/2 speed of GraalVM). There is a lot of calls between Java and Python with a Constraint Streams which I can't do anything about unless I reimplement OptaPlanner in Python (which I do not want to do). Using a EasyConstraintProvider might actually be faster than Constraint Streams for this situlation (since it only one transfer per score calculation versus several ; no benchmarking done yet). The speeds are pretty good considering the transfer between Java/Python (I'm not expecting it to match GraalVM speeds; that is pretty close to impossible). However, even the speed that the GraalVM implementation runs at is too slow for most use cases. The only way I see to increase the speed to the point of it being usable is to make the user pass strings which are compiled into Java functions and don't go back into Python once the Solver starts. However, then the user cannot use NumPy, their own functions, etc. and don't get IDE support.

**Comment by Christopher-Chianelli** [comment]
(another note on `__getattr__` on a `JImplementationFor`: returning a python Object will yield a TypeError: Return value is not compatible with required type. I can't use a JProxy here since the same code is also called within Python code, which doesn't know how to get attributes from the JProxy (thus I needed to create PythonRef)); additionally the same object must map to the same PythonRef for constraints to work.

**Comment by Thrameos** [comment]
Sounds like the issue with speed is trying to use Python code to implement a functional interface which is being called in a tight loop within the optimizer.   That is certainly an issue as the cost of Java calling Python code requires a lot of marshalling (look up the function, do the type equivalence of each argument, execute the Python code, then marshal the return type).   There may be some potential improvements on that path but admittedly it will always be pretty heavy.   There may be some potential caching there but I really don't see more than 20% savings unless I missed something really drastic.

My approach if I was doing this particular problem using the  ``epypj`` branch would be to use the fact that all Python methods can be executed from within Java to convert the Python byte code into a equivalent Java bytecode which calls through jpyffi.   Depending on the code complexity and the amount of optimizations that can be performed it may be possible to get close to native Java speed.   If the bytecode contains unrecognized codes that can't be translated then it just falls back to the old slower path of marshalling to Python.   Unfortunately I only made some initial stabs at that  because the Python bytecode is way less stable than Java so I wasn't sure I wanted to try that for long term support.   But in theory the JImplements could check each each method to see if the Python byte codes can be optimized to Java bytecodes and place a stub that repoints to Java in place of the Python version.   The byte code translator can be written in Java (faster) or Python (more flexible) and use the ASM.   But as it stands until JPype includes jpyffi (Java to Python foreign function interface) we are pretty limited in how to address this.

The unpleasant alternative is to use a Factory that allows the user to create Java code from within Python by assembling commands to make a Functional interface object of some kind.   That defeats the point of writing in Python syntax and unworkable if the classes to be implemented are not lambdas.   Alternatively using the Java compiler to implement short sections of code loaded in the classpath is workable, but undesirable from the user prospective.   Calling the Java compiler from within Python to produce a class is slow and only works if a full copy of the JDK is available.

**Comment by Christopher-Chianelli** [comment]
@Thrameos Thanks for the tips and comments. If I was determined enough to try to make it usable, I do think the python bytecode -> java bytecode is a good approach (I already do a fair bit of Java bytecode writing). However, it is a lot of work (Python has over 100 bytecode instructions). I'm merging this PR; if I have any further problems/suggestions, I will post them to the JPype repo.

**Pull request merged**
