### PR TITLE
optapy#126: Enable Dependabot

### PR DESCRIPTION
**Pull request by Christopher-Chianelli**

### CODE REVIEW

**Review by triceo — APPROVED** [review]
Let's see what happens after we merge.

**Comment by Christopher-Chianelli** [comment]
It seems to be mostly working for Java; although we probably don't want it to do pr for `optaplanner-build-parent` (since the OptaPy version is tied to the OptaPlanner version). For Python, unknown, since our only dependency is `JPype1>=1.4.0` (https://github.com/optapy/optapy/blob/28c0bf2b881321f81754604c8f9b4226be202a1c/setup.py#L140), which matches JPype 1.4.1 (the current version of JPype) (https://pypi.org/project/JPype1/).

**Comment by Christopher-Chianelli** [comment]
From the update checker log for Python, it found `JPype1`, and said no update possible for it:

```
updater | INFO <job_539443448> Starting job processing
updater | INFO <job_539443448> Starting update job for optapy/optapy
updater | INFO <job_539443448> Checking if jpype1  needs updating
  proxy | 2022/12/08 20:41:00 [028] GET https://pypi.org:443/simple/jpype1/
  proxy | 2022/12/08 20:41:00 [028] 200 https://pypi.org:443/simple/jpype1/
updater | INFO <job_539443448> Latest version is 1.4.1
  proxy | 2022/12/08 20:41:00 [030] GET https://pypi.org:443/simple/jpype1/
  proxy | 2022/12/08 20:41:00 [030] 200 https://pypi.org:443/simple/jpype1/
updater | INFO <job_539443448> Requirements to unlock update_not_possible
updater | INFO <job_539443448> Requirements update strategy bump_versions
updater | INFO <job_539443448> No update possible for jpype1 
updater | INFO <job_539443448> Finished job processing
```

**Comment by Christopher-Chianelli** [comment]
Seems to be expected behavior; since the version is not pinned in Python (and allow later versions), no pr is generated: https://github.com/dependabot/dependabot-core/issues/2894

**Pull request merged**
